#!/bin/bash

name=$(jq -r '.name' data.json)
name="${name^}"
type=$(jq -r '.types[0].type.name' data.json)
type="${type^}"
weight=$(jq -r '.weight' data.json)
height=$(jq -r '.height' data.json)

formatted_weight=$(echo " $weight / 10" | bc)
formatted_height=$(printf "%.1f" "$(echo "$height / 10" | bc -l)")
echo "$name is of type $type, weighs ${formatted_weight}kg, and is ${formatted_height}m tall."
